# Generated by Django 2.2.1 on 2019-08-06 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('date_time', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('PROGRESS', 'in_progress'), ('COMP', 'completed'), ('PEND', 'pending')], default='PROGRESS', max_length=20)),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 8, 6, 17, 50, 44, 516768, tzinfo=utc))),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
