# Generated by Django 2.2.1 on 2019-08-06 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 17, 50, 59, 277371, tzinfo=utc)),
        ),
    ]
