# Generated by Django 2.0 on 2019-08-06 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190806_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 18, 24, 46, 186476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoclass',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
