# Generated by Django 2.0 on 2019-08-07 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190806_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 3, 12, 26, 740232)),
        ),
    ]
